# Rhize Plugins

## Skill Usage (IMPORTANT)

This project contains Claude Code skills (plugins). When a user's request matches an available skill's description, you MUST invoke it using the Skill tool rather than handling the request with general knowledge and native tools.

**Rules:**
- Check the available skills list before responding to any user request
- If a skill's trigger description matches the user's intent, invoke it with the Skill tool immediately
- Do NOT attempt to replicate skill functionality using WebFetch, Bash, or other tools when a matching skill exists
- Skills contain specialized workflows, API integrations, and output formats that general-purpose tool use cannot replicate

**Available skill categories:**

*SEO/AEO/GEO plugin:*
- SEO auditing and analysis (`seo-site-audit`)
- Keyword research and intelligence (`keyword-intelligence`)
- Backlink analysis (`backlink-intelligence`)
- SERP checking and monitoring (`serp-intelligence`)
- Content SEO optimization (`content-seo`)
- AI/Answer Engine Optimization (`aeo-geo-optimization`)
- Next.js + Sanity SEO review (`nextjs-sanity-seo`)

*Obsidian Skills plugin:*
- Obsidian CLI operations (`obsidian-cli`)
- Obsidian markdown syntax (`obsidian-markdown`)
- Obsidian Bases database views (`obsidian-bases`)
- JSON Canvas visual boards (`json-canvas`)
- Web clipping with Defuddle (`defuddle`)
- Second brain / PKM methodology (`second-brain`)
- Vault note templates (`vault-templates`)
- Vault health and alignment (`vault-alignment`)

*Project Launcher plugin:*
- Full project launch pipeline — research, PRD, gap analysis, scaffold, GSD v2 handoff (`project-launcher`)
- Commands: `/launch-project`, `/write-prd`, `/scaffold-gsd`, `/grill-prd`

## Headroom Learned Patterns
*Auto-generated by `headroom learn` on 2026-06-16 — do not edit manually*

### Fact-Forcing Gate: Edit Commands
*~2,800 tokens/session saved*
- **Before every Edit, run `grep -rl "<basename>" .` to enumerate all files that import/require it**, then present that list in a preceding Bash FACTS echo — the gate blocks any Edit that omits this step.
- Four blocked Edits in one session (SKILL.md, monitor.py, CLAUDE.md, MEMORY.md) — always satisfy the gate before the Edit tool call, not after.

### Repo Structure: skill-monitor Consolidation
*~2,000 tokens/session saved*
- `skill-monitor` has been consolidated into the rhize-ops plugin at `rhize-ops/skill-monitor/monitor.py`. The old standalone repo `~/dev-local/skill-monitor/` is archived on GitHub and deleted locally — never reference the old path.
- The weekly-skill-audit scheduled task has been repointed to `rhize-ops/skill-monitor/monitor.py`; data paths inside monitor.py are `__file__`-relative.

### Fact-Forcing Gate: Bash Commands
*~1,400 tokens/session saved*
- **Prefix every first Bash command each session (and after any `mcp__ccd_session__mark_chapter` call) with an inline FACTS echo**: `echo "FACTS: (1) <user request in one sentence>; (2) <what this command verifies/produces>" &&` — skipping this blocks the command and wastes a round-trip.
- The gate re-arms after each chapter mark, so the first Bash after each new phase also needs the FACTS prefix.
- Bypass for pure repair/setup work: set `ECC_GATEGUARD=off`.

### Fact-Forcing Gate: Write (New Files)
*~1,400 tokens/session saved*
- **Before creating a new file with Write, identify which existing files will call or reference it** and state them in a Bash FACTS echo first — the gate demands: "Name the file(s) and line(s) that will call this file."
- If no existing caller yet, state that explicitly: `echo "FACTS: new entry point — no existing caller."`
