import {isoDateTime, realDate} from '../domain.mjs';
const timestamp = value => { isoDateTime(value, 'interval time'); return Date.parse(value); };
function localParts(instant, timeZone) { const values = Object.fromEntries(new Intl.DateTimeFormat('en-CA', {timeZone, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23'}).formatToParts(new Date(instant)).filter(part => part.type !== 'literal').map(part => [part.type, part.value])); return `${values.year}-${values.month}-${values.day}T${values.hour}:${values.minute}`; }
function zonedInstant(date, time, timeZone) { const desired = `${date}T${time}`; const naive = Date.parse(`${desired}:00.000Z`); if (timeZone === 'UTC') return new Date(naive).toISOString(); const matches = []; for (let instant = naive - 50400000; instant <= naive + 50400000; instant += 60000) if (localParts(instant, timeZone) === desired) matches.push(instant); if (matches.length !== 1) throw new RangeError(`${desired} is nonexistent or ambiguous in ${timeZone}`); return new Date(matches[0]).toISOString(); }
export function materializeWorkingIntervals(profile, planningDate, intervals = profile.workingIntervals) { realDate(planningDate, 'planningDate'); const day = new Date(`${planningDate}T00:00:00.000Z`).getUTCDay() || 7; return intervals.filter(interval => interval.dayOfWeek === day).map(interval => ({start: zonedInstant(planningDate, interval.start, profile.identity.timezone), end: zonedInstant(planningDate, interval.end, profile.identity.timezone)})); }
export function overlaps(left, right) { return timestamp(left.start) < timestamp(right.end) && timestamp(right.start) < timestamp(left.end); }
export function totalMinutes(intervals) { return intervals.reduce((total, interval) => total + Math.round((timestamp(interval.end) - timestamp(interval.start)) / 60000), 0); }
export function assertProtectedIntervals(intervals) { if (!Array.isArray(intervals)) throw new TypeError('protectedIntervals must be an array'); intervals.forEach((interval, index) => { if (!interval || typeof interval !== 'object' || typeof interval.id !== 'string' || !['fixed', 'outside', 'break', 'manual_lock', 'freeze'].includes(interval.kind) || !['calendar', 'reminders', 'local'].includes(interval.sourceSystem) || interval.mutable !== false) throw new TypeError(`protectedIntervals[${index}] is invalid`); if (timestamp(interval.start) >= timestamp(interval.end)) throw new RangeError(`protectedIntervals[${index}] start must precede end`); }); return intervals; }
export function subtractIntervals(windows, protectedIntervals) { const cuts = [...protectedIntervals].sort((left, right) => timestamp(left.start) - timestamp(right.start)); return windows.flatMap(window => cuts.reduce((pieces, cut) => pieces.flatMap(piece => { if (!overlaps(piece, cut)) return [piece]; const result = []; if (timestamp(piece.start) < timestamp(cut.start)) result.push({start: piece.start, end: new Date(timestamp(cut.start)).toISOString()}); if (timestamp(cut.end) < timestamp(piece.end)) result.push({start: new Date(timestamp(cut.end)).toISOString(), end: piece.end}); return result; }), [{...window}]).filter(piece => timestamp(piece.start) < timestamp(piece.end))); }
