import {isoDateTime, realDate} from '../domain.mjs';
import {classifyTask} from './eligibility.mjs';
import {estimateTask} from './estimates.mjs';
import {assertProtectedIntervals, materializeWorkingIntervals, subtractIntervals, totalMinutes} from './intervals.mjs';
import {rankTasks} from './priority.mjs';
const minutesBetween = (start, end) => Math.round((Date.parse(end) - Date.parse(start)) / 60000);
function localDate(instant, timeZone) { const parts = Object.fromEntries(new Intl.DateTimeFormat('en-CA', {timeZone, year: 'numeric', month: '2-digit', day: '2-digit'}).formatToParts(new Date(instant)).filter(part => part.type !== 'literal').map(part => [part.type, part.value])); return `${parts.year}-${parts.month}-${parts.day}`; }
function reasonFor(task, classification, estimate) { if (task.manualLock) return 'manual_lock'; if (task.blocked) return 'blocked'; if (task.lane === 'provisional' || classification?.lane === 'provisional') return 'provisional'; if (task.reserved) return 'reserved'; if (classification?.lane === 'opportunity') return 'opportunity_unapproved'; if (!classification) return 'ineligible'; if (estimate.confidence === 'low' || estimate.requiresApproval) return 'low_confidence'; return null; }
function trimBefore(windows, cutoff) { return windows.flatMap(window => Date.parse(window.end) <= cutoff ? [] : [{start: Date.parse(window.start) < cutoff ? new Date(cutoff).toISOString() : window.start, end: window.end}]); }
function place(task, estimate, windows, profile, planRevision, blocks) { const windowSnapshot = windows.map(window => ({...window})); const blockCount = blocks.length; let remaining = estimate.minutes; let sessionIndex = 0; for (let index = 0; index < windows.length && remaining > 0; index += 1) { const window = windows[index]; const available = minutesBetween(window.start, window.end); if (available < profile.planning.minimumBlockMinutes) continue; const amount = Math.min(remaining, available, profile.planning.focusBlockMinutes); if (amount < profile.planning.minimumBlockMinutes) continue; sessionIndex += 1; const start = window.start; const end = new Date(Date.parse(start) + amount * 60000).toISOString(); blocks.push({id: `${planRevision}:${task.id}:${sessionIndex}`, taskId: task.id, start, end, minutes: amount, sessionIndex, contextKey: task.competencies.map(name => name.toLowerCase()).sort().join('|') || '~', locked: false}); windows[index] = {start: end, end: window.end}; remaining -= amount; if (!profile.planning.allowSplitting && remaining > 0) break; } if (remaining !== 0) { windows.splice(0, windows.length, ...windowSnapshot); blocks.splice(blockCount); return false; } return true; }
export function planDay({tasks, protectedIntervals, profile, history = [], planningDate, now, planRevision}) { realDate(planningDate, 'planningDate'); isoDateTime(now, 'now'); if (!Number.isInteger(planRevision) || planRevision < 1) throw new RangeError('planRevision must be an integer >= 1'); assertProtectedIntervals(protectedIntervals); const today = localDate(now, profile.identity.timezone); if (planningDate < today) throw new RangeError('planningDate must not be in the past'); const protectedCopy = structuredClone(protectedIntervals); const recurringBreaks = materializeWorkingIntervals(profile, planningDate, profile.breaks); let windows = subtractIntervals(materializeWorkingIntervals(profile, planningDate), [...protectedCopy, ...recurringBreaks]); const beforeFreeze = totalMinutes(windows); if (planningDate === today) windows = trimBefore(windows, Date.parse(now) + profile.planning.freezeWindowMinutes * 60000); const availableMinutes = totalMinutes(windows); const capacityMinutes = Math.min(profile.capacity.maxDailyMinutes, Math.floor(availableMinutes * (1 - profile.capacity.bufferPercent / 100))); const bufferMinutes = availableMinutes - capacityMinutes; const enriched = tasks.map(task => ({...task, estimate: estimateTask(task, history, profile)})); const ranking = rankTasks(enriched, profile, now); const blocks = []; const unscheduled = []; let remainingCapacity = capacityMinutes; for (const item of ranking) { const reason = reasonFor(item.task, classifyTask(item.task, profile), item.estimate); if (reason) { unscheduled.push({taskId: item.task.id, reason}); continue; } if (item.estimate.minutes > remainingCapacity || !place(item.task, item.estimate, windows, profile, planRevision, blocks)) { unscheduled.push({taskId: item.task.id, reason: beforeFreeze > availableMinutes && item.estimate.minutes <= beforeFreeze ? 'freeze_window' : 'no_capacity'}); continue; } remainingCapacity -= item.estimate.minutes; } const usedMinutes = blocks.reduce((total, block) => total + block.minutes, 0); return {schemaVersion: 1, planRevision, planningDate, generatedAt: now, status: 'preview', availableMinutes, capacityMinutes, usedMinutes, bufferMinutes, ranked: ranking.map(item => ({taskId: item.task.id, lane: item.lane, schedulable: item.schedulable, factors: item.factors, estimate: item.estimate})), blocks, unscheduled, protectedIntervals: protectedCopy}; }
