/**
 * esbuild.config.mjs — bundle the Obsidian plugin.
 *
 * Bundles src/main.ts -> main.js (CJS, the format Obsidian's plugin loader
 * expects). React, react-dom, @mdx-js/mdx, @mdx-js/react, mermaid, gray-matter
 * and the remark-* plugins are bundled IN (Obsidian provides none of them).
 * `obsidian`, `electron`, and Node builtins are marked external — the Electron
 * host provides them at runtime.
 *
 * The viewer's stylesheet (../../viewer/src/styles.css) is imported as text in
 * src/main.ts (the `.css` -> text loader below) and injected as a <style> at
 * load. We ALSO emit a standalone styles.css next to main.js so the plugin can
 * be installed by copying manifest.json + main.js + styles.css (the Obsidian
 * convention) — see the build step at the bottom.
 *
 * NOTE: the imported component/helper modules live OUTSIDE this directory
 * (../../viewer/src/*.tsx). esbuild follows the relative import and compiles the
 * TSX in place — there is exactly ONE copy of the components, shared with the
 * CLI viewer. The .tsx loader covers them.
 */

import esbuild from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { builtinModules } from "node:module";

// Node core modules, with and without the "node:" prefix, marked external so
// any (transitive) reference to fs/path/etc. is left for the host, not bundled.
const builtins = [...builtinModules, ...builtinModules.map((m) => `node:${m}`)];

const __dirname = dirname(fileURLToPath(import.meta.url));
const production = process.argv[2] === "production";

const VIEWER_CSS = resolve(__dirname, "../viewer/src/styles.css");

const banner = `/*
 * Rhize Visual Plan — Obsidian plugin (generated by esbuild, do not edit).
 * Renderer core reused from ../viewer/src/*.tsx (one core, many shells).
 */`;

/** @type {import('esbuild').BuildOptions} */
const options = {
  banner: { js: banner },
  entryPoints: [resolve(__dirname, "src/main.ts")],
  bundle: true,
  // Bundle these IN — Obsidian/Electron do not provide them.
  // Externalize the host-provided modules.
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  // Dedupe React to a SINGLE copy. The renderer core is imported across folders
  // (../viewer/src/*), and the viewer has its OWN node_modules/react; without
  // this alias esbuild bundles TWO React copies → "Invalid hook call" → blank
  // render. Force every react / react-dom / @mdx-js/react import (incl. subpaths
  // like react/jsx-runtime, react-dom/client) to THIS plugin's node_modules.
  // The Vite viewer build does the equivalent via resolve.alias + dedupe.
  alias: {
    react: resolve(__dirname, "node_modules/react"),
    "react-dom": resolve(__dirname, "node_modules/react-dom"),
    "@mdx-js/react": resolve(__dirname, "node_modules/@mdx-js/react"),
  },
  format: "cjs",
  target: "es2020",
  platform: "browser",
  // The viewer's .tsx (PlanShell/components) is authored for the AUTOMATIC JSX
  // runtime (it does NOT import a `React` global into scope — Vite's React
  // plugin defaults to automatic). So we must use the automatic transform here
  // too; the classic transform would throw "React is not defined" at render.
  // esbuild auto-imports jsx/jsxs/Fragment from `react/jsx-runtime` (bundled in).
  jsx: "automatic",
  loader: {
    ".css": "text",
    ".tsx": "tsx",
    ".ts": "ts",
  },
  // gray-matter and some remark deps reference `process` / Buffer-ish globals;
  // define a minimal process.env so they don't crash in the Electron renderer.
  define: {
    "process.env.NODE_ENV": production ? '"production"' : '"development"',
    global: "window",
  },
  sourcemap: production ? false : "inline",
  treeShaking: true,
  logLevel: "info",
  outfile: resolve(__dirname, "main.js"),
};

async function run() {
  if (production) {
    await esbuild.build(options);
    // Emit the standalone styles.css (Obsidian install convention) from the
    // SAME viewer stylesheet we inline, so the two never diverge.
    writeFileSync(
      resolve(__dirname, "styles.css"),
      readFileSync(VIEWER_CSS, "utf8"),
    );
    console.log("[rhize-visual-plan] build complete: main.js + styles.css");
  } else {
    const ctx = await esbuild.context(options);
    await ctx.watch();
    console.log("[rhize-visual-plan] watching for changes…");
  }
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
