import {connectorError, normalizeError, unsupported} from './http.mjs';

const terminal = new Set(['done', 'closed', 'resolved', 'cancelled']);
const esc = value => String(value).replaceAll('\\', '\\\\').replaceAll('"', '\\"');
const priority = value => ({highest: 'urgent', high: 'high', medium: 'normal', low: 'low', lowest: 'low'})[String(value ?? '').toLowerCase()] ?? 'normal';
export const textToAdf = text => ({type: 'doc', version: 1, content: [{type: 'paragraph', content: [{type: 'text', text: String(text)}]}]});
export const adfToText = value => typeof value === 'string' ? value : value?.content?.flatMap(node => node.content ?? []).filter(node => node.type === 'text').map(node => node.text).join('') ?? '';

export function createJiraConnector({baseUrl, accountId, projectKeys, issueTypes, credentials, transport} = {}) {
  if (!baseUrl || !accountId || !Array.isArray(projectKeys) || !Array.isArray(issueTypes) || !credentials?.get || typeof transport !== 'function') throw new TypeError('invalid Jira connector configuration');
  const projects = new Set(projectKeys); const types = new Set(issueTypes);
  async function request(path, options = {}) { try { const [email, token] = await Promise.all([credentials.get('media.rhize.tasks.jira', 'email'), credentials.get('media.rhize.tasks.jira', 'api-token')]); const result = await transport({url: new URL(path, baseUrl).toString(), method: options.method ?? 'GET', headers: {authorization: `Basic ${Buffer.from(`${email}:${token}`).toString('base64')}`, accept: 'application/json', ...(options.body ? {'content-type': 'application/json'} : {})}, body: options.body ? JSON.stringify(options.body) : undefined}); if (!result || result.status < 200 || result.status >= 300) throw connectorError(result?.status === 401 || result?.status === 403 ? 'authorization' : 'http', {status: result?.status, retryable: result?.status >= 500 || result?.status === 429}); return result; } catch (error) { throw normalizeError(error, {afterWrite: options.method && options.method !== 'GET'}); } }
  async function tokenPage(path) { const out = []; const seen = new Set(); let token = null; for (let count = 0; count < 100; count += 1) { const url = path + (path.includes('?') ? '&' : '?') + (token ? `nextPageToken=${encodeURIComponent(token)}` : 'maxResults=50'); const body = (await request(url)).body; const values = body.issues ?? body.values ?? []; out.push(...values); token = body.nextPageToken; if (!token) return out; if (seen.has(token)) throw connectorError('pagination_loop'); seen.add(token); } throw connectorError('pagination_limit'); }
  async function scopedIssue(key) { const issue = (await request(`/rest/api/3/issue/${encodeURIComponent(key)}?fields=project,issuetype,assignee,status,updated`)).body; if (!projects.has(issue.fields?.project?.key) || !types.has(issue.fields?.issuetype?.name)) throw connectorError('out_of_scope'); return issue; }
  async function searchByJql(jql) { return tokenPage(`/rest/api/3/search/jql?jql=${encodeURIComponent(jql)}&fields=${encodeURIComponent('key,updated')}`); }
  function createLabel(key) { return `rhize-op-${key}`.slice(0, 255); }
  async function preexistingCreate(key) { const items = await searchByJql(`labels = "${esc(createLabel(key))}"`); return items[0] ?? null; }
  const api = {
    async health() { await request('/rest/api/3/myself'); return {ok: true}; },
    async discover() { const [projectList, issueTypes, priorities, account] = await Promise.all([tokenPage('/rest/api/3/project/search'), request('/rest/api/3/issuetype'), request('/rest/api/3/priority'), request('/rest/api/3/myself')]); return {projects: projectList.filter(item => projects.has(item.key) && !item.archived), issueTypes: (issueTypes.body ?? []).filter(item => types.has(item.name)), priorities: priorities.body ?? [], account: account.body}; },
    async readSnapshot() { const jql = `project in (${projectKeys.map(value => `"${esc(value)}"`).join(',')}) AND issuetype in (${issueTypes.map(value => `"${esc(value)}"`).join(',')}) AND statusCategory != Done ORDER BY updated DESC`; const issues = await tokenPage(`/rest/api/3/search/jql?jql=${encodeURIComponent(jql)}&fields=${encodeURIComponent('summary,project,issuetype,assignee,priority,duedate,status,created,updated,timetracking,description')}`); return issues.filter(i => projects.has(i.fields?.project?.key) && types.has(i.fields?.issuetype?.name) && !terminal.has(String(i.fields?.status?.name).toLowerCase())).map(i => ({schemaVersion: 1, id: i.id, sourceType: 'jira', lane: i.fields.assignee?.accountId === accountId ? 'owned' : 'opportunity', title: i.fields.summary, projectKey: i.fields.project.key, issueType: i.fields.issuetype.name, assigneeAccountId: i.fields.assignee?.accountId ?? null, priority: priority(i.fields.priority?.name), dueDate: i.fields.duedate ?? null, status: i.fields.status?.name ?? 'Unknown', terminal: false, blocked: false, dependencyRisk: 0, remainingMinutes: i.fields.timetracking?.remainingEstimateSeconds ? Math.ceil(i.fields.timetracking.remainingEstimateSeconds / 60) : null, explicitEstimateMinutes: null, competencies: [], manualLock: false, carryoverCount: 0, createdAt: i.fields.created, reserved: false, sourceRevision: String(i.fields.updated ?? i.version ?? i.id), jiraKey: i.key, jiraUrl: new URL(`/browse/${i.key}`, baseUrl).toString(), description: adfToText(i.fields.description)})); },
    async applyOperation(operation) { try { if (!operation || !['jira_assign', 'jira_transition', 'jira_comment', 'jira_create'].includes(operation.kind)) unsupported(); if (operation.kind === 'jira_create') { if (!projects.has(operation.payload.projectKey) || !types.has(operation.payload.issueType)) throw connectorError('out_of_scope'); const found = await preexistingCreate(operation.idempotencyKey); if (found) return {externalId: found.key, revision: String(found.fields?.updated ?? found.id ?? found.key)}; try { const response = await request('/rest/api/3/issue', {method: 'POST', body: {fields: {project: {key: operation.payload.projectKey}, issuetype: {name: operation.payload.issueType}, summary: operation.payload.title, description: textToAdf(operation.payload.description), duedate: operation.payload.dueDate, priority: {name: operation.payload.priority}, labels: [createLabel(operation.idempotencyKey)]}}}); return {externalId: response.body.key, revision: String(response.body.id ?? response.body.key)}; } catch (error) { if (error.ambiguous) { const created = await preexistingCreate(operation.idempotencyKey); if (created) return {externalId: created.key, revision: String(created.fields?.updated ?? created.id ?? created.key)}; } throw error; } } const issue = await scopedIssue(operation.targetId); if (operation.kind === 'jira_assign') { if (issue.fields.assignee?.accountId === operation.payload.accountId) return {externalId: operation.targetId, revision: String(issue.fields.updated)}; await request(`/rest/api/3/issue/${encodeURIComponent(operation.targetId)}/assignee`, {method: 'PUT', body: {accountId: operation.payload.accountId}}); } else if (operation.kind === 'jira_comment') { const marker = `rhize-operation:${operation.idempotencyKey}`; const comments = (await request(`/rest/api/3/issue/${encodeURIComponent(operation.targetId)}/comment?maxResults=100`)).body.comments ?? []; if (!comments.some(comment => adfToText(comment.body).includes(marker))) await request(`/rest/api/3/issue/${encodeURIComponent(operation.targetId)}/comment`, {method: 'POST', body: {body: textToAdf(`${operation.payload.body}\n${marker}`)}}); } else { const transitions = (await request(`/rest/api/3/issue/${encodeURIComponent(operation.targetId)}/transitions`)).body.transitions ?? []; if (!transitions.some(item => item.id === operation.payload.transitionId)) throw connectorError('transition_unavailable'); await request(`/rest/api/3/issue/${encodeURIComponent(operation.targetId)}/transitions`, {method: 'POST', body: {transition: {id: operation.payload.transitionId}, ...(operation.payload.comment ? {update: {comment: [{add: {body: textToAdf(`${operation.payload.comment}\nrhize-operation:${operation.idempotencyKey}`)}}]}} : {})}}); } const found = await api.findByExternalId(operation.targetId); return {externalId: operation.targetId, revision: found?.revision ?? String(issue.fields.updated)}; } catch (error) { throw normalizeError(error, {afterWrite: true}); } },
    async findByExternalId(externalId) { try { const issue = (await request(`/rest/api/3/issue/${encodeURIComponent(externalId)}?fields=updated`)).body; return {revision: String(issue.fields?.updated ?? issue.version ?? issue.id)}; } catch (error) { if (error.status === 404) return null; throw normalizeError(error); } },
  };
  return api;
}
