import {connectorError, normalizeError, unsupported} from './http.mjs';

const terminal = new Set(['done', 'closed', 'resolved', 'cancelled']);
const priority = value => ({highest: 'urgent', high: 'high', medium: 'normal', low: 'low', lowest: 'low'})[String(value ?? '').toLowerCase()] ?? 'normal';
const page = async (request, path) => { const all = []; for (let startAt = 0;;) { const body = (await request(path + (path.includes('?') ? '&' : '?') + `startAt=${startAt}&maxResults=50`)).body; const values = body.values ?? body.issues ?? []; all.push(...values); if (body.isLast || all.length >= (body.total ?? 0) || values.length === 0) return all; startAt += values.length; } };

export function createJiraConnector({baseUrl, accountId, projectKeys, issueTypes, credentials, transport} = {}) {
  if (!baseUrl || !accountId || !Array.isArray(projectKeys) || !Array.isArray(issueTypes) || !credentials?.get || typeof transport !== 'function') throw new TypeError('invalid Jira connector configuration');
  const allowedProjects = new Set(projectKeys); const allowedTypes = new Set(issueTypes);
  async function request(path, options = {}) { const [email, token] = await Promise.all([credentials.get('media.rhize.tasks.jira', 'email'), credentials.get('media.rhize.tasks.jira', 'api-token')]); try { return await transport({url: new URL(path, baseUrl).toString(), method: options.method ?? 'GET', headers: {authorization: `Basic ${Buffer.from(`${email}:${token}`).toString('base64')}`, accept: 'application/json', ...(options.body ? {'content-type': 'application/json'} : {})}, body: options.body ? JSON.stringify(options.body) : undefined}); } catch (error) { throw normalizeError(error, {afterWrite: options.method && options.method !== 'GET'}); } }
  const api = {
    async health() { await request('/rest/api/3/myself'); return {ok: true}; },
    async discover() { const [projects, types, priorities, me] = await Promise.all([page(request, '/rest/api/3/project/search'), request('/rest/api/3/issuetype'), request('/rest/api/3/priority'), request('/rest/api/3/myself')]); return {projects: projects.filter(p => allowedProjects.has(p.key) && p.archived !== true), issueTypes: (types.body ?? []).filter(t => allowedTypes.has(t.name)), priorities: priorities.body ?? [], account: me.body}; },
    async readSnapshot() { const p = projectKeys.map(value => `"${String(value).replaceAll('"', '\\"')}"`).join(','); const t = issueTypes.map(value => `"${String(value).replaceAll('"', '\\"')}"`).join(','); const jql = `project in (${p}) AND issuetype in (${t}) AND statusCategory != Done ORDER BY updated DESC`; const issues = await page(request, `/rest/api/3/search/jql?jql=${encodeURIComponent(jql)}&fields=${encodeURIComponent('summary,project,issuetype,assignee,priority,duedate,status,statuscategory,created,updated,timetracking,description')}`); return issues.filter(i => allowedProjects.has(i.fields.project?.key) && allowedTypes.has(i.fields.issuetype?.name) && !terminal.has(String(i.fields.status?.name).toLowerCase())).map(i => ({schemaVersion: 1, id: i.id, sourceType: 'jira', lane: i.fields.assignee?.accountId === accountId ? 'owned' : 'opportunity', title: i.fields.summary, projectKey: i.fields.project.key, issueType: i.fields.issuetype.name, assigneeAccountId: i.fields.assignee?.accountId ?? null, priority: priority(i.fields.priority?.name), dueDate: i.fields.duedate ?? null, status: i.fields.status?.name ?? 'Unknown', terminal: false, blocked: false, dependencyRisk: 0, remainingMinutes: i.fields.timetracking?.remainingEstimateSeconds ? Math.ceil(i.fields.timetracking.remainingEstimateSeconds / 60) : null, explicitEstimateMinutes: null, competencies: [], manualLock: false, carryoverCount: 0, createdAt: i.fields.created, reserved: false, sourceRevision: String(i.fields.updated ?? i.version ?? i.id), jiraKey: i.key, jiraUrl: new URL(`/browse/${i.key}`, baseUrl).toString(), description: typeof i.fields.description === 'string' ? i.fields.description : ''})); },
    async applyOperation(operation) { try { if (!operation?.kind?.startsWith('jira_')) unsupported(); if (operation.kind === 'jira_assign') await request(`/rest/api/3/issue/${encodeURIComponent(operation.targetId)}/assignee`, {method: 'PUT', body: {accountId: operation.payload.accountId}}); else if (operation.kind === 'jira_comment') await request(`/rest/api/3/issue/${encodeURIComponent(operation.targetId)}/comment`, {method: 'POST', body: {body: operation.payload.body, properties: [{key: 'rhizeOperationKey', value: operation.idempotencyKey}]}}); else if (operation.kind === 'jira_transition') { const transitions = (await request(`/rest/api/3/issue/${encodeURIComponent(operation.targetId)}/transitions`)).body.transitions ?? []; if (!transitions.some(t => t.id === operation.payload.transitionId)) throw connectorError('transition_unavailable'); await request(`/rest/api/3/issue/${encodeURIComponent(operation.targetId)}/transitions`, {method: 'POST', body: {transition: {id: operation.payload.transitionId}, ...(operation.payload.comment ? {update: {comment: [{add: {body: operation.payload.comment}}]}} : {})}}); } else if (operation.kind === 'jira_create') { if (!allowedProjects.has(operation.payload.projectKey) || !allowedTypes.has(operation.payload.issueType)) throw connectorError('out_of_scope'); const result = await request('/rest/api/3/issue', {method: 'POST', body: {fields: {project: {key: operation.payload.projectKey}, issuetype: {name: operation.payload.issueType}, summary: operation.payload.title, description: operation.payload.description, duedate: operation.payload.dueDate, labels: [`rhize-op-${operation.idempotencyKey}`]}}}); return {externalId: result.body.key, revision: String(result.body.id ?? result.body.key)}; } else unsupported(); const found = await api.findByExternalId(operation.targetId); return {externalId: operation.targetId, revision: found?.revision ?? operation.idempotencyKey}; } catch (error) { throw normalizeError(error, {afterWrite: true}); } },
    async findByExternalId(externalId) { try { const issue = (await request(`/rest/api/3/issue/${encodeURIComponent(externalId)}?fields=updated`)).body; return {revision: String(issue.fields?.updated ?? issue.version ?? issue.id)}; } catch (error) { if (error?.status === 404) return null; throw normalizeError(error); } },
  };
  return api;
}
